---
name: "Bug report"
description: "Report a bug with the iopool integration"
title: "[Bug]:  "
labels: [bug]
assignees: mguyard
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        >
        > This issue form is for reporting bugs only!
        >
        > Before you open a new issue, search through the [existing issues][ei] to see if others have had the same problem.
        >
        > [ei]: https://github.com/mguyard/hass-iopool/issues?q=label%3Abug


  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  
  - type: textarea
    attributes:
      label: Reproduction steps
      description: "Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part, issues without it will be closed"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true



  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    attributes:
      label: What was the last working version of Home Assistant Core?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core



  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        Many integrations provide the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for the device you are having issues with,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: text
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.


  - type: markdown
    attributes:
      value: |
        ## Confirmation
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have filled out the issue template to the best of my ability.
          required: true
        - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
          required: true
        - label: This issue is not a duplicate issue of currently [previous issues](https://github.com/mguyard/hass-iopool/issues?q=label%3Abug)..
          required: true