---
name: Home Assistant Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  schedule:
    - cron: '0 1 * * *'

jobs:
  validate-hassfest:
    name: Hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  test:
    name: Run Tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      
      - name: Run tests with pytest
        run: |
          pytest tests/ -v --cov=custom_components.iopool --cov-report=term-missing
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella