---
name: Home Assistant Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches:
      - main
      - beta
      - dev

jobs:
  validate-hassfest:
    name: Hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"