---
name: Lock & Stale Issues and Pull Requests

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  lock: # Lock inactive issues and pull requests
    if: github.repository_owner == 'mguyard'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5.0.1
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          issue-lock-reason: ''
          pr-inactive-days: '30'
          pr-lock-reason: ''
          log-output: true

  stale: # Mark stale issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          any-of-issue-labels: "waiting-for-response"
          days-before-issue-stale: 30
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been automatically marked as abandoned because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          exempt-issue-labels: "no-stale, bug, documentation"
    